=== unexist/deskbar/xml/config.dtd
<!ELEMENT display (plugin | text | meter)+>
<!ATTLIST display
	version		CDATA		#REQUIRED
	>

<!ELEMENT plugin EMPTY>
<!ATTLIST plugin
	name			CDATA			#REQUIRED
	id				CDATA			#IMPLIED
	options		CDATA			#IMPLIED
	interval	CDATA			#REQUIRED
	>

<!ELEMENT text EMPTY>
<!ATTLIST text
	x					CDATA			#REQUIRED
	y					CDATA			#REQUIRED
	font			CDATA			#IMPLIED
	size			CDATA			#IMPLIED
	color			CDATA			#IMPLIED
	value			CDATA			#IMPLIED
	data			CDATA			#IMPLIED
	>

<!ELEMENT meter EMPTY>
<!ATTLIST meter
	x					CDATA			#REQUIRED
	y					CDATA			#REQUIRED
	color			CDATA			#IMPLIED
	width			CDATA			#REQUIRED
	height		CDATA			#IMPLIED
	data			CDATA			#REQUIRED
	>

=== unexist/deskbar/xml/config.xml
<?xml version="1.0"?>
<!-- <!DOCTYPE display SYSTEM "/usr/local/share/deskbar/config.dtd"> -->
<display version="0.2">
	<plugin name="time" id="p1" options="%H.%M" interval="2" />
	<plugin name="cpu" id="p2" interval="10" />
	<plugin name="battery" id="p3" interval="600" />
	
	<text x="5" y="0" font="luxi sans" size="35" color="white" data="p1" />

	<text x="110" y="10" font="luxi sans" size="10" color="white" value="[ CPU:                                           ]" />
	<text x="110" y="25" font="luxi sans" size="10" color="white" value="[ Battery:                                      ]" />
	
	<text x="160" y="10" font="luxi sans" size="10" color="white" data="p2" />
	<text x="160" y="25" font="luxi sans" size="10" color="white" data="p3" />

	<meter x="220" y="13" color="white" width="42" height="8" data="p2" />
	<meter x="220" y="28" color="white" width="42" height="8" data="p3" />
</display>
